name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Check .NET project version
      working-directory: ./MicroClient/MicroClient
      run: |
        VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" MicroClient.csproj)
        echo "Found project version: $VERSION"
        if [ -z "$VERSION" ]; then
          echo "No <Version> found in MicroClient.csproj!"
          exit 1
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build .NET project
      working-directory: ./MicroClient/MicroClient
      run: dotnet build --configuration Release

    - name: Publish .NET project
      working-directory: ./MicroClient/MicroClient
      run: dotnet publish -c Release -o ./publish

    - name: Log in to Docker Hub
      run: echo "${{ secrets.docker_hub_pass }}" | docker login -u "${{ secrets.docker_hub_name }}" --password-stdin

    - name: Build Docker image
      working-directory: ./MicroClient/MicroClient
      run: |
        docker build . -f Dockerfile \
          -t ${{ secrets.docker_hub_name }}/micro-client:${VERSION} \
          -t ${{ secrets.docker_hub_name }}/micro-client:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.docker_hub_name }}/micro-client:${VERSION}
        docker push ${{ secrets.docker_hub_name }}/micro-client:latest

